spring.config.import=optional:file:./fetchrate.properties
spring.application.name=FetchRate
spring.main.banner-mode=off
server.port=8000
server.address=0.0.0.0
spring.datasource.url=jdbc:sqlite:data/exchange_rates.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.connection-test-query=SELECT 1
ecb.fiat.daily-url=https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml
ecb.fiat.full-url=https://www.ecb.europa.eu/stats/eurofxref/eurofxref-hist.xml
ecb.fiat.days90-url=https://www.ecb.europa.eu/stats/eurofxref/eurofxref-hist-90d.xml

livecoinwatch.api-key=${LIVECOINWATCH_API_KEY:}
fetchrate.crypto-dir=data/crypto