spring.application.name=FetchRate
spring.main.banner-mode=off
logging.level.root=OFF
spring.main.lazy-initialization=true
spring.main.web-application-type=none
spring.main.log-startup-info=false
spring.jmx.enabled=false
spring.devtools.add-properties=false
spring.datasource.url=jdbc:sqlite:data/exchange_rates.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.connection-test-query=SELECT 1
ecb.fiat.daily-url=https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml
ecb.fiat.full-url=https://www.ecb.europa.eu/stats/eurofxref/eurofxref-hist.xml
ecb.fiat.days90-url=https://www.ecb.europa.eu/stats/eurofxref/eurofxref-hist-90d.xml
