spring.application.name=FetchRate
ecb.fiat.daily-url=https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml
ecb.fiat.full-url=https://www.ecb.europa.eu/stats/eurofxref/eurofxref-hist.xml
ecb.fiat.days90-url=https://www.ecb.europa.eu/stats/eurofxref/eurofxref-hist-90d.xml